### ISSUE TITLE
Why ActiveRecord?

### ISSUE THREAD

**Issue by nizsheanez** [allain/activerecorditerator#1]
It iterrator can working with ever IDataProvider implemented class like CSqlDataProvider.

**Comment by allain** [comment]
I suppose ignorance is the answer.

What do you suggest as a name?

**Comment by nizsheanez** [comment]
I suggest DataProviderIterator and in the code suggest replace the CActiveDataProvider on IDataProvider interface.

**Comment by allain** [comment]
sounds good. thanks for the feedback
